version: 1

services:
  - type: web
    name: evoltsoft-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: AUTH_RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: AUTH_RATE_LIMIT_MAX_REQUESTS
        value: 5
      - key: BCRYPT_ROUNDS
        value: 12
    healthCheckPath: /health
    autoDeploy: true
